package fr.sii.sonar.duplication.simian.provider;

import fr.sii.sonar.duplication.simian.domain.Simian;
import fr.sii.sonar.duplication.simian.domain.Simian.Check.Set;
import fr.sii.sonar.duplication.simian.domain.Simian.Check.Set.Block;
import fr.sii.sonar.report.core.common.provider.ReportAdapter;
import fr.sii.sonar.report.core.duplication.domain.DuplicatedBlock;
import fr.sii.sonar.report.core.duplication.domain.DuplicationGroup;
import fr.sii.sonar.report.core.duplication.domain.DuplicationReport;

/**
 * Adapter that transforms raw xml report generated by Simian into a
 * {@link DuplicationReport} usable by Sonar.
 * 
 * @author Aurélien Baudet
 *
 */
public class SimianAdapter implements ReportAdapter<DuplicationReport, Simian> {

	public DuplicationReport adapt(Simian source) {
		DuplicationReport report = new DuplicationReport();
		for(Set set : source.getCheck().getSet()) {
			DuplicationGroup group = new DuplicationGroup();
			for(Block block : set.getBlock()) {
				group.addDuplicatedBlock(new DuplicatedBlock(block.getSourceFile(), block.getStartLineNumber(), block.getEndLineNumber()));
			}
			report.addDuplicationGroup(group);
		}
		return report;
	}
}

